// <auto-generated />
using Djm.OGame.Web.Api.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;

namespace Djm.OGame.Web.Api.Dal.Data.Migrations
{
    [DbContext(typeof(OGameContext))]
    partial class OGameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Djm.OGame.Web.Api.Dal.Models.Pin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("OwnerId");

                    b.Property<int>("TargetId");

                    b.Property<int>("UniverseId");

                    b.HasKey("Id");

                    b.HasIndex("UniverseId", "OwnerId", "TargetId")
                        .IsUnique();

                    b.ToTable("Pins");
                });
#pragma warning restore 612, 618
        }
    }
}
